-- Entity audit logs: track field-level changes with old/new values (JSON text)
-- Separate from the HTTP request audit_log (V3). This tracks domain entity mutations.
CREATE TABLE entity_audit_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type    VARCHAR(100)  NOT NULL,
    entity_id      BIGINT        NOT NULL,
    action         VARCHAR(20)   NOT NULL,
    changed_by     VARCHAR(100)  NOT NULL,
    old_value      TEXT,
    new_value      TEXT,
    changed_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_entity_audit_action CHECK (action IN ('CREATE', 'UPDATE', 'DELETE'))
);

CREATE INDEX idx_entity_audit_entity ON entity_audit_log (entity_type, entity_id);
CREATE INDEX idx_entity_audit_changed_at ON entity_audit_log (changed_at);
CREATE INDEX idx_entity_audit_changed_by ON entity_audit_log (changed_by);

-- Remote actions: commands sent to devices with timeout tracking.
-- Lifecycle: PENDING -> CONFIRMED / EXPIRED / FAILED
-- 5-minute expiry: if device does not confirm within 5 min, action expires.
-- No duplicate PENDING actions of same type per device.
CREATE TABLE remote_action (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id     BIGINT       NOT NULL,
    action_type   VARCHAR(50)  NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    payload       TEXT,
    result        TEXT,
    issued_by     VARCHAR(100) NOT NULL,
    issued_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at    TIMESTAMP    NOT NULL,
    confirmed_at  TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_remote_action_device FOREIGN KEY (device_id) REFERENCES device(id),
    CONSTRAINT chk_remote_action_status CHECK (status IN ('PENDING', 'CONFIRMED', 'EXPIRED', 'FAILED')),
    CONSTRAINT chk_remote_action_expiry CHECK (expires_at > issued_at)
);

CREATE INDEX idx_remote_action_device ON remote_action (device_id);
CREATE INDEX idx_remote_action_status ON remote_action (status);
CREATE INDEX idx_remote_action_expires ON remote_action (expires_at);
CREATE INDEX idx_remote_action_device_type_status ON remote_action (device_id, action_type, status);
