-- Playback logs: records of content actually played on devices.
-- Deduplicated by (device_id, content_file_id, played_at) at DB level.
CREATE TABLE playback_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id        BIGINT    NOT NULL,
    content_file_id  BIGINT    NOT NULL,
    assignment_id    BIGINT,
    played_at        TIMESTAMP NOT NULL,
    duration_seconds INTEGER,
    reported_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_playback_device FOREIGN KEY (device_id) REFERENCES device(id),
    CONSTRAINT fk_playback_content FOREIGN KEY (content_file_id) REFERENCES content_file(id),
    CONSTRAINT fk_playback_assignment FOREIGN KEY (assignment_id) REFERENCES content_assignment(id),
    CONSTRAINT uq_playback_dedup UNIQUE (device_id, content_file_id, played_at)
);

CREATE INDEX idx_playback_device ON playback_log (device_id, played_at);
CREATE INDEX idx_playback_content ON playback_log (content_file_id);
CREATE INDEX idx_playback_assignment ON playback_log (assignment_id);
CREATE INDEX idx_playback_played_at ON playback_log (played_at);
