-- Application users: replaces the in-memory user store.
-- Role and active status stored in DB, checked on login and per-request.
CREATE TABLE app_user (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(100) NOT NULL UNIQUE,
    password    VARCHAR(200) NOT NULL,
    role        VARCHAR(20)  NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_user_role CHECK (role IN ('ADMIN', 'OPERATOR', 'VIEWER', 'ADVERTISER'))
);

CREATE INDEX idx_user_username ON app_user (username);
CREATE INDEX idx_user_active ON app_user (is_active);

-- Advertiser-content access: links advertisers to content files they can view.
-- An advertiser with no rows here sees an empty dashboard, not an error.
CREATE TABLE advertiser_content_access (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    content_file_id BIGINT NOT NULL,
    granted_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    granted_by      VARCHAR(100) NOT NULL,
    CONSTRAINT fk_adv_access_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_adv_access_content FOREIGN KEY (content_file_id) REFERENCES content_file(id),
    CONSTRAINT uq_adv_access UNIQUE (user_id, content_file_id)
);

CREATE INDEX idx_adv_access_user ON advertiser_content_access (user_id);
CREATE INDEX idx_adv_access_content ON advertiser_content_access (content_file_id);

-- Seed default dev users
INSERT INTO app_user (username, password, role, is_active) VALUES ('developabror@gmail.com', 'password', 'ADMIN', TRUE);
INSERT INTO app_user (username, password, role, is_active) VALUES ('admin', 'password', 'ADMIN', TRUE);
INSERT INTO app_user (username, password, role, is_active) VALUES ('operator', 'password', 'OPERATOR', TRUE);
INSERT INTO app_user (username, password, role, is_active) VALUES ('viewer', 'password', 'VIEWER', TRUE);
INSERT INTO app_user (username, password, role, is_active) VALUES ('advertiser', 'password', 'ADVERTISER', TRUE);
INSERT INTO app_user (username, password, role, is_active) VALUES ('deactivated', 'password', 'VIEWER', FALSE);
