CREATE TABLE health_check_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component   VARCHAR(100)  NOT NULL,
    status      VARCHAR(20)   NOT NULL,
    checked_at  TIMESTAMP     NOT NULL,
    details     VARCHAR(500)
);
