-- Operator project scoping + per-operator content ownership.
--
-- 1) project_operator: assigns OPERATOR users to one or more projects. An operator with no
--    rows here sees an empty hierarchy (fail-closed), never the whole system. The project FK
--    cascades on project delete; the user FK does NOT cascade (the user-delete path clears
--    these rows at the service layer, mirroring advertiser_content_access).
CREATE TABLE project_operator (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    assigned_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by VARCHAR(100) NOT NULL,
    CONSTRAINT uq_project_operator UNIQUE (project_id, user_id),
    CONSTRAINT fk_project_operator_project FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE,
    CONSTRAINT fk_project_operator_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE INDEX idx_project_operator_user ON project_operator (user_id);
CREATE INDEX idx_project_operator_project ON project_operator (project_id);

-- 2) operator_content_access: structural clone of advertiser_content_access. Links an OPERATOR
--    to content files an admin granted them (ownership via content_file.uploaded_by is the other
--    visibility path). The content FK is intentionally NON-cascading on purpose; do NOT add
--    ON DELETE CASCADE — content is soft-deleted (content_file.deleted_at), never row-removed,
--    and query-time filters suppress soft-deleted grants.
CREATE TABLE operator_content_access (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    content_file_id BIGINT NOT NULL,
    granted_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    granted_by      VARCHAR(100) NOT NULL,
    CONSTRAINT fk_op_content_access_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_op_content_access_content FOREIGN KEY (content_file_id) REFERENCES content_file(id),
    CONSTRAINT uq_op_content_access UNIQUE (user_id, content_file_id)
);

CREATE INDEX idx_op_content_access_user ON operator_content_access (user_id);
CREATE INDEX idx_op_content_access_content ON operator_content_access (content_file_id);

-- 3) content_file.uploaded_by: the username that uploaded a file. Drives per-operator ownership
--    (an operator sees a file iff they uploaded it OR were granted access). Existing rows keep
--    NULL (legacy/system); no backfill.
ALTER TABLE content_file ADD COLUMN uploaded_by VARCHAR(100);

CREATE INDEX idx_content_file_uploaded_by ON content_file (uploaded_by);
