CREATE TABLE audit_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal       VARCHAR(100)  NOT NULL,
    http_method     VARCHAR(10)   NOT NULL,
    path            VARCHAR(500)  NOT NULL,
    response_status INTEGER       NOT NULL,
    request_body    TEXT,
    response_body   TEXT,
    timestamp       TIMESTAMP     NOT NULL
);

CREATE INDEX idx_audit_log_timestamp ON audit_log (timestamp);
CREATE INDEX idx_audit_log_principal ON audit_log (principal, timestamp);
