-- V40: server-anchored playback schedule (Variant A). One row per assignment content-version.
-- Devices in a sync group derive "what is on screen right now" as a pure function of synced time
-- from a shared anchor + slot timings; only anchor_epoch_ms and activate_at are non-derivable, so
-- they are persisted here ONCE per (assignment_id, version_number) and never move for that version's
-- life. loop_duration_ms and per-item slots are computed on the fly from the playlist at /sync time.
-- anchor_epoch_ms is epoch MILLISECONDS (overflows INT) → BIGINT. activate_at is the same instant as
-- a TIMESTAMP for human/ops legibility. No soft-delete: a schedule row is immutable and tiny.
-- assignment_id references content_assignment(id) (never hard-deleted); kept FK-free to mirror the
-- V22 version-tracking columns and keep the coordinated-cut-over write path allocation-cheap.
-- H2 PG-mode for tests, Postgres in prod — both accept this DDL (identity PK precedent: V4/V6/V21).

CREATE TABLE playback_sync_schedule (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id   BIGINT      NOT NULL,
    version_number  INT         NOT NULL,
    content_version VARCHAR(64) NOT NULL,
    anchor_epoch_ms BIGINT      NOT NULL,   -- == activate_at epoch ms; the loop's T0
    activate_at     TIMESTAMP   NOT NULL,   -- coordinated cut-over instant
    created_at      TIMESTAMP   NOT NULL,
    CONSTRAINT uq_playback_sched UNIQUE (assignment_id, version_number)
);
