-- SyncGroup: a project-scoped "sales point" grouping used by the synchronized-playback
-- layer. Distinct from region/facility/device_group — one sales point = one sync group.
-- A Device may belong to at most one sync group (nullable FK); the group sits at the TOP
-- of Device.getSyncGroupId()'s derivation chain (sg- > fac- > grp- > reg-), so the device
-- wire stays an opaque string and the Android app needs no change.
--
-- HARD delete (no deleted_at): the delete path requires zero active members, sync groups
-- are never assignment targets, and playback_sync_schedule does not reference them — so the
-- UNIQUE(project_id, name) constraint is exact (no soft-deleted rows lingering in it).

CREATE TABLE sync_group (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT       NOT NULL,
    name        VARCHAR(200) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sync_group_project FOREIGN KEY (project_id) REFERENCES project(id),
    CONSTRAINT uq_sync_group_name_per_project UNIQUE (project_id, name)
);
CREATE INDEX idx_sync_group_project ON sync_group(project_id);

ALTER TABLE device ADD COLUMN sync_group_id BIGINT;
ALTER TABLE device ADD CONSTRAINT fk_device_sync_group
    FOREIGN KEY (sync_group_id) REFERENCES sync_group(id);
CREATE INDEX idx_device_sync_group ON device(sync_group_id);

-- Recreate device_status_view to expose d.sync_group_id (DeviceListItem is built from this
-- view, and the FE sync-group picker needs the numeric sync_group_id per device row).
--
-- DROP + CREATE (not CREATE OR REPLACE): changing a view's column list is not portable
-- across H2 and PostgreSQL via REPLACE (see V34/V16's own notes). Every V34 column is
-- re-listed verbatim plus d.sync_group_id; the active-assignment predicate still appears
-- THREE times (active_playlist_id, active_playlist_name, computed_status) and MUST stay
-- character-identical — a fidelity test pins that all three agree on every row.
DROP VIEW IF EXISTS device_status_view;
CREATE VIEW device_status_view AS
SELECT
    d.id, d.region_id, d.facility_id, f.name AS facility_name, d.device_group_id, d.sync_group_id,
    d.serial_number, d.name, d.last_heartbeat_at, d.created_at, d.updated_at,

    -- (1) winning active playlist id — mirrors resolveForDevice .max(priority), tie-broken id DESC
    (SELECT ca.playlist_id FROM content_assignment ca
       WHERE ca.deleted_at IS NULL AND ca.status = 'CONFIRMED'
         AND ca.start_time <= CURRENT_TIMESTAMP AND ca.end_time > CURRENT_TIMESTAMP
         AND ( (ca.target_type='REGION'       AND ca.target_id = d.region_id)
            OR (ca.target_type='FACILITY'     AND ca.target_id = d.facility_id)
            OR (ca.target_type='DEVICE_GROUP' AND ca.target_id = d.device_group_id) )
         AND NOT EXISTS (SELECT 1 FROM content_assignment_exclusion x
                          WHERE x.assignment_id = ca.id AND x.device_id = d.id)
       ORDER BY ca.priority DESC, ca.id DESC FETCH FIRST 1 ROW ONLY) AS active_playlist_id,

    -- (2) that winning playlist's name (same predicate, joined to playlist)
    (SELECT p.name FROM content_assignment ca JOIN playlist p ON p.id = ca.playlist_id
       WHERE ca.deleted_at IS NULL AND ca.status = 'CONFIRMED'
         AND ca.start_time <= CURRENT_TIMESTAMP AND ca.end_time > CURRENT_TIMESTAMP
         AND ( (ca.target_type='REGION'       AND ca.target_id = d.region_id)
            OR (ca.target_type='FACILITY'     AND ca.target_id = d.facility_id)
            OR (ca.target_type='DEVICE_GROUP' AND ca.target_id = d.device_group_id) )
         AND NOT EXISTS (SELECT 1 FROM content_assignment_exclusion x
                          WHERE x.assignment_id = ca.id AND x.device_id = d.id)
       ORDER BY ca.priority DESC, ca.id DESC FETCH FIRST 1 ROW ONLY) AS active_playlist_name,

    -- (3) computed_status — CONFIRMED + exclusion-aware (unchanged from V34)
    CASE
      WHEN d.last_heartbeat_at IS NULL THEN 'OFFLINE'
      WHEN d.last_heartbeat_at < CURRENT_TIMESTAMP - INTERVAL '16' MINUTE THEN 'OFFLINE'
      WHEN NOT EXISTS (
          SELECT 1 FROM content_assignment ca
           WHERE ca.deleted_at IS NULL AND ca.status = 'CONFIRMED'
             AND ca.start_time <= CURRENT_TIMESTAMP AND ca.end_time > CURRENT_TIMESTAMP
             AND ( (ca.target_type='REGION'       AND ca.target_id = d.region_id)
                OR (ca.target_type='FACILITY'     AND ca.target_id = d.facility_id)
                OR (ca.target_type='DEVICE_GROUP' AND ca.target_id = d.device_group_id) )
             AND NOT EXISTS (SELECT 1 FROM content_assignment_exclusion x
                              WHERE x.assignment_id = ca.id AND x.device_id = d.id)
      ) THEN 'NO_CONTENT'
      ELSE 'ONLINE'
    END AS computed_status
FROM device d
LEFT JOIN facility f ON f.id = d.facility_id
WHERE d.deleted_at IS NULL;
