-- V42: operator "jump the whole sync group to item N". A MUTABLE re-anchor that overrides the
-- immutable per-version anchor (V40 playback_sync_schedule) for one sync group. Applies only while
-- the group stays on (assignment_id, version_number, content_version); a version change makes it
-- stale and it is ignored (and cleaned up) at /sync time. Hard delete; cascades with the group.
-- H2 PG-mode for tests, Postgres in prod — both accept this DDL (identity PK precedent: V4/V6/V21;
-- ON DELETE CASCADE precedent: V6/V7/V35). Unlike V40 this row is mutable, hence updated_at.
CREATE TABLE sync_group_playback_override (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_group_id   BIGINT      NOT NULL,
    assignment_id   BIGINT      NOT NULL,
    version_number  INT         NOT NULL,
    content_version VARCHAR(64) NOT NULL,
    chosen_index    INT         NOT NULL,   -- 0-based deliverable index the operator picked (audit)
    anchor_epoch_ms BIGINT      NOT NULL,   -- re-anchored loop T0 = activate_at_ms − slotStart[idx]
    activate_at     TIMESTAMP   NOT NULL,   -- coordinated cut-over instant
    created_at      TIMESTAMP   NOT NULL,
    updated_at      TIMESTAMP   NOT NULL,
    CONSTRAINT uq_sg_pb_override UNIQUE (sync_group_id),
    CONSTRAINT fk_sg_pb_override_group FOREIGN KEY (sync_group_id)
        REFERENCES sync_group(id) ON DELETE CASCADE
);
