-- V43: remote view/control sessions. A session is a short-lived rendezvous between one
-- operator browser and one device, brokered by an external relay. The backend mints it,
-- pushes it to the device, and records the outcome; it never carries media.
--
-- Why not reuse remote_action: that table's 5-min DEFAULT_TIMEOUT, one-PENDING-per-type
-- rule, once-and-terminal confirm and RemoteActionExpirationJob would all fight a
-- long-lived session. remote_action initiates things; this table holds one.
--
-- H2 PG-mode for tests, Postgres in prod — both accept this DDL. Identity PK precedent:
-- V4/V6/V10/V21/V42. TEXT + CHECK precedent: V10. BOOLEAN NOT NULL DEFAULT precedent: V12.
-- NOTE: deliberately NO partial unique index for "one live session per device" — H2 does not
-- support them. That rule is enforced in the service layer, exactly as remote_action's
-- one-PENDING-per-type rule already is.
CREATE TABLE remote_session (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_key    VARCHAR(64)  NOT NULL,   -- "rs_" + 16 random bytes hex; NEVER the device id
    device_id      BIGINT       NOT NULL,
    status         VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    view_only      BOOLEAN      NOT NULL DEFAULT FALSE,
    issued_by      VARCHAR(100) NOT NULL,   -- username, matching remote_action.issued_by
    issued_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at     TIMESTAMP    NOT NULL,
    started_at     TIMESTAMP,               -- set on the device's READY ack
    ended_at       TIMESTAMP,
    end_reason     VARCHAR(64),             -- OPERATOR_STOP | DEVICE_ENDED | EXPIRED | DEVICE_FAILED
    error          TEXT,
    device_width   INT,
    device_height  INT,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_remote_session_key UNIQUE (session_key),
    CONSTRAINT fk_remote_session_device FOREIGN KEY (device_id) REFERENCES device(id),
    CONSTRAINT chk_remote_session_status
        CHECK (status IN ('PENDING','ACTIVE','ENDED','FAILED','EXPIRED')),
    CONSTRAINT chk_remote_session_expiry CHECK (expires_at > issued_at)
);

CREATE INDEX idx_remote_session_device_status ON remote_session (device_id, status);
CREATE INDEX idx_remote_session_expires ON remote_session (expires_at);

-- Device-reported remote capability. Refreshed on every heartbeat; NULL = never reported.
-- Capability is reported, not assumed: it lets the operator UI degrade to view-only
-- without any contract change if input injection turns out not to work on a box.
-- All columns nullable, so no backfill is needed (ALTER precedent: V38).
ALTER TABLE device ADD COLUMN remote_supported  BOOLEAN;
ALTER TABLE device ADD COLUMN remote_input      VARCHAR(16);   -- ROOT | ACCESSIBILITY | NONE
ALTER TABLE device ADD COLUMN remote_transport  VARCHAR(24);   -- SCRCPY_WS | NONE
ALTER TABLE device ADD COLUMN remote_max_width  INT;
ALTER TABLE device ADD COLUMN remote_max_height INT;
ALTER TABLE device ADD COLUMN remote_caps_at    TIMESTAMP;
