-- Projects: top-level organizational unit
CREATE TABLE project (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Regions: belong to a project
CREATE TABLE region (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT       NOT NULL,
    name        VARCHAR(200) NOT NULL,
    code        VARCHAR(50)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_region_project FOREIGN KEY (project_id) REFERENCES project(id),
    CONSTRAINT uq_region_code_per_project UNIQUE (project_id, code)
);

-- Facilities: belong to a region. Name unique within region.
CREATE TABLE facility (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id   BIGINT       NOT NULL,
    name        VARCHAR(200) NOT NULL,
    address     VARCHAR(500),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_facility_region FOREIGN KEY (region_id) REFERENCES region(id),
    CONSTRAINT uq_facility_name_per_region UNIQUE (region_id, name)
);

-- Devices: belong to a region. RESTRICT delete on region with active devices.
CREATE TABLE device (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id   BIGINT       NOT NULL,
    facility_id BIGINT,
    serial_number VARCHAR(100) NOT NULL UNIQUE,
    name        VARCHAR(200) NOT NULL,
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_device_region FOREIGN KEY (region_id) REFERENCES region(id) ON DELETE RESTRICT,
    CONSTRAINT fk_device_facility FOREIGN KEY (facility_id) REFERENCES facility(id)
);

CREATE INDEX idx_device_region ON device (region_id);
CREATE INDEX idx_device_facility ON device (facility_id);
CREATE INDEX idx_facility_region ON facility (region_id);
CREATE INDEX idx_region_project ON region (project_id);
