-- Device Groups: logical grouping of devices within a region
CREATE TABLE device_group (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id   BIGINT       NOT NULL,
    name        VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at  TIMESTAMP,
    CONSTRAINT fk_device_group_region FOREIGN KEY (region_id) REFERENCES region(id),
    CONSTRAINT uq_device_group_name_per_region UNIQUE (region_id, name)
);

CREATE INDEX idx_device_group_region ON device_group (region_id);

-- Add soft delete and device_group FK to device table
ALTER TABLE device ADD COLUMN deleted_at TIMESTAMP;
ALTER TABLE device ADD COLUMN device_group_id BIGINT;
ALTER TABLE device ADD CONSTRAINT fk_device_device_group
    FOREIGN KEY (device_group_id) REFERENCES device_group(id);

-- Change status default to UNREGISTERED
ALTER TABLE device ALTER COLUMN status SET DEFAULT 'UNREGISTERED';

-- serial_number remains globally unique at DB level (from V4 UNIQUE constraint).
-- Soft-deleted devices retain their serial_number — re-registration requires
-- the application to clear the old record or use a new serial.

CREATE INDEX idx_device_device_group ON device (device_group_id);
CREATE INDEX idx_device_deleted_at ON device (deleted_at);
