-- Content files: media assets uploaded to the system
CREATE TABLE content_file (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   BIGINT       NOT NULL,
    name         VARCHAR(300) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes   BIGINT       NOT NULL,
    storage_key  VARCHAR(500) NOT NULL,
    checksum     VARCHAR(64),
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at   TIMESTAMP,
    CONSTRAINT fk_content_file_project FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE INDEX idx_content_file_project ON content_file (project_id);
CREATE INDEX idx_content_file_deleted ON content_file (deleted_at);

-- Playlists: ordered collection of content files
CREATE TABLE playlist (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT       NOT NULL,
    name        VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at  TIMESTAMP,
    CONSTRAINT fk_playlist_project FOREIGN KEY (project_id) REFERENCES project(id),
    CONSTRAINT uq_playlist_name_per_project UNIQUE (project_id, name)
);

CREATE INDEX idx_playlist_project ON playlist (project_id);

-- Playlist items: join table with position ordering
-- Position is unique within a playlist (no two items at same position)
CREATE TABLE playlist_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlist_id     BIGINT  NOT NULL,
    content_file_id BIGINT  NOT NULL,
    position        INTEGER NOT NULL,
    duration_seconds INTEGER,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_playlist_item_playlist FOREIGN KEY (playlist_id) REFERENCES playlist(id) ON DELETE CASCADE,
    CONSTRAINT fk_playlist_item_content FOREIGN KEY (content_file_id) REFERENCES content_file(id),
    CONSTRAINT uq_playlist_position UNIQUE (playlist_id, position)
);

CREATE INDEX idx_playlist_item_playlist ON playlist_item (playlist_id, position);
CREATE INDEX idx_playlist_item_content ON playlist_item (content_file_id);
