-- Content assignments: assign a playlist to a target (REGION, FACILITY, or DEVICE_GROUP)
-- with a time range. Priority rule: DEVICE_GROUP > FACILITY > REGION.
CREATE TABLE content_assignment (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlist_id  BIGINT       NOT NULL,
    target_type  VARCHAR(20)  NOT NULL,
    target_id    BIGINT       NOT NULL,
    priority     INTEGER      NOT NULL,
    start_time   TIMESTAMP    NOT NULL,
    end_time     TIMESTAMP    NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at   TIMESTAMP,
    CONSTRAINT fk_assignment_playlist FOREIGN KEY (playlist_id) REFERENCES playlist(id),
    CONSTRAINT chk_assignment_time_range CHECK (end_time > start_time),
    CONSTRAINT chk_assignment_target_type CHECK (target_type IN ('REGION', 'FACILITY', 'DEVICE_GROUP'))
);

CREATE INDEX idx_assignment_target ON content_assignment (target_type, target_id);
CREATE INDEX idx_assignment_playlist ON content_assignment (playlist_id);
CREATE INDEX idx_assignment_time ON content_assignment (start_time, end_time);
CREATE INDEX idx_assignment_deleted ON content_assignment (deleted_at);

-- Exclusion: exclude specific devices from an assignment
CREATE TABLE content_assignment_exclusion (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id   BIGINT NOT NULL,
    device_id       BIGINT NOT NULL,
    reason          VARCHAR(500),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_exclusion_assignment FOREIGN KEY (assignment_id) REFERENCES content_assignment(id) ON DELETE CASCADE,
    CONSTRAINT fk_exclusion_device FOREIGN KEY (device_id) REFERENCES device(id),
    CONSTRAINT uq_exclusion_per_device UNIQUE (assignment_id, device_id)
);

CREATE INDEX idx_exclusion_assignment ON content_assignment_exclusion (assignment_id);
CREATE INDEX idx_exclusion_device ON content_assignment_exclusion (device_id);
