-- Schedules: time windows for content assignments with optional repeat patterns.
-- All datetimes stored in UTC. Display conversion to UTC+5 is application-level only.
CREATE TABLE schedule (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id   BIGINT       NOT NULL,
    start_time_utc  TIMESTAMP    NOT NULL,
    end_time_utc    TIMESTAMP    NOT NULL,
    repeat_type     VARCHAR(20)  NOT NULL DEFAULT 'NONE',
    repeat_end_utc  TIMESTAMP,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP,
    CONSTRAINT fk_schedule_assignment FOREIGN KEY (assignment_id) REFERENCES content_assignment(id),
    CONSTRAINT chk_schedule_time_range CHECK (end_time_utc > start_time_utc),
    CONSTRAINT chk_schedule_repeat_type CHECK (repeat_type IN ('NONE', 'DAILY', 'WEEKLY', 'MONTHLY')),
    CONSTRAINT chk_schedule_repeat_end CHECK (
        (repeat_type = 'NONE' AND repeat_end_utc IS NULL) OR
        (repeat_type <> 'NONE' AND repeat_end_utc IS NOT NULL AND repeat_end_utc > end_time_utc)
    )
);

CREATE INDEX idx_schedule_assignment ON schedule (assignment_id);
CREATE INDEX idx_schedule_time ON schedule (start_time_utc, end_time_utc);
CREATE INDEX idx_schedule_deleted ON schedule (deleted_at);
