-- Events: discrete occurrences reported by devices or the system
CREATE TABLE event (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id   BIGINT       NOT NULL,
    event_type  VARCHAR(50)  NOT NULL,
    priority    VARCHAR(20)  NOT NULL,
    payload     TEXT,
    occurred_at TIMESTAMP    NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_event_device FOREIGN KEY (device_id) REFERENCES device(id),
    CONSTRAINT chk_event_priority CHECK (priority IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'))
);

CREATE INDEX idx_event_device ON event (device_id);
CREATE INDEX idx_event_type ON event (event_type);
CREATE INDEX idx_event_occurred ON event (occurred_at);
CREATE INDEX idx_event_priority ON event (priority);

-- Incidents: represent an ongoing issue tied to a device and event type.
-- Lifecycle: OPEN -> ACKNOWLEDGED -> RESOLVED
-- One open incident per device per event type (enforced at application level
-- since H2 does not support partial unique indexes; PostgreSQL production
-- would add: CREATE UNIQUE INDEX ... WHERE status <> 'RESOLVED').
CREATE TABLE incident (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id       BIGINT       NOT NULL,
    event_type      VARCHAR(50)  NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    priority        VARCHAR(20)  NOT NULL,
    description     VARCHAR(1000),
    occurrence_count INTEGER     NOT NULL DEFAULT 1,
    first_event_id  BIGINT       NOT NULL,
    last_event_id   BIGINT       NOT NULL,
    opened_at       TIMESTAMP    NOT NULL,
    acknowledged_at TIMESTAMP,
    resolved_at     TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_incident_device FOREIGN KEY (device_id) REFERENCES device(id),
    CONSTRAINT fk_incident_first_event FOREIGN KEY (first_event_id) REFERENCES event(id),
    CONSTRAINT fk_incident_last_event FOREIGN KEY (last_event_id) REFERENCES event(id),
    CONSTRAINT chk_incident_status CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED')),
    CONSTRAINT chk_incident_priority CHECK (priority IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'))
);

CREATE INDEX idx_incident_device ON incident (device_id);
CREATE INDEX idx_incident_status ON incident (status);
CREATE INDEX idx_incident_device_type_status ON incident (device_id, event_type, status);
